// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdydzhpskpmjzsoznxsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeWR6aHBza3Btanpzb3pueHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDk4NDksImV4cCI6MjA2NDkyNTg0OX0.JvG5vrfC_kV93RCojq0YMKyCp28kh4EeNA7-FmmNOBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);